### PR TITLE
/entity/unrevised: Show button to show more revisions

### PR DESCRIPTION
**Pull request by kulla**
Closes https://github.com/serlo/serlo.org/issues/637: 
2021-05-18-192502_694x339_scrot

### CODE REVIEW

**Comment by kulla** [comment]
@inyono Can you show me again what I need to do for i18n?

**Comment by inyono** [comment]
- Update the translation file from source code (E.g. Poedit works well because it has PHP and Twig support). See my commit for the changes.
- Upload the translation file to Crowdin.
- Translate on Crowdin.
- Export translations (you can ping me for that because I have a script for that).

**Review by inyono — APPROVED** [review]
LGTM. Probably still makes sense to do the i18n stuff before merging.

**Comment by kulla** [comment]
> * Update the translation file from source code (E.g. Poedit works well because it has PHP and Twig support). See my commit for the changes.

With which command? `yarn i18n:regenerate` hasn't worked for me...

> * Export translations (you can ping me for that because I have a script for that).

Can you add this script into this repo or is this not possible?!

**Comment by inyono** [comment]
- `yarn i18n:regenerate` is only for the the client i18n. The server i18n has no CLI, unfortunately (because the twig-stuff has no good CLI). This is why we use Poedit for that.

- I could add that script to the repo but I would need to change it up so that it works on non-macOS and that it pulls the API token from somewhere.

Since we don't update i18n often and have a good solution for the new frontend, I never prioritized to make this process easier. If you feel that this is necessary, I can look into that.

**Comment by kulla** [comment]
> Since we don't update i18n often and have a good solution for the new frontend, I never prioritized to make this process easier. If you feel that this is necessary, I can look into that.

Let's see whether we need it more often...

**Pull request merged**
