### PR TITLE
Fixing loading font from root path

### PR DESCRIPTION
**Pull request by Entkenntnis**
Ok, it's quite an obvious solution

### CODE REVIEW

**Comment by inyono** [comment]
How does this affect SSR?

**Comment by Entkenntnis** [comment]
ssr will work as usual, by "runtime" i mean the react runtime: the font path is loaded when a new globalstyle element is created and not, when globalstyle itself is created (which happens on file-load and at this moment the assetPath is not set yet)

**Comment by inyono** [comment]
I suppose this is no longer relevant because of serlo/frontend, right?

**Comment by Entkenntnis** [comment]
Yes

**Pull request closed without merging**
