### PR TITLE
API: add support for threads

### PR DESCRIPTION
**Pull request by kulla**
Add support for threads into the api (see https://github.com/serlo/api.serlo.org/issues/22 ).

* A request to `/api/threads/:id` returns a list of ids to comments for the uuid `:id`. When `:id` is no valid uuid an empty list is returned. Example result:

```json
{
  "firstCommentIds": [
    41443,
    60067
  ]
}
```

* Requests to `/api/uuid/:id` also return properties of a comment. Example result:

```json
{
  "id": 60067,
  "trashed": false,
  "alias": null,
  "__typename": "Comment",
  "authorId": 52009,
  "title": "Verbesserungsvorschläge",
  "date": "2016-07-26T15:40:44+02:00",
  "archived": false,
  "content": "Liebes Serlo-Team\r\n\r\nhier ein paar kleine Sachen, die an diesem Artikel verbessert werden können: \r\n\r\n- Die Verlinkungen in den Überschriften entfernen\r\n- Den Begriff Distributivgesetz verlinken\r\n- Die Aufgaben im Spoiler mit einer Aufgabenstellung versehen\r\n- Die Aufgaben der Schwierigkeit nach sortieren (v.a. die mit den quadratischen Termen zum Schluss)\r\n- Den Teil zur Linearfaktorzerlegung entfernen\r\n\r\nViele Grüße\r\nSebastian ",
  "parentId": 1605,
  "childrenIds": [
    60150
  ]
}
```

`parentId` is an uuid (article, course, ...) when the comment is the first comment of a thread and thus directly attached to the article and an other comment, when the comment is a following comment of a thread (for example an answer to the first comment).

### CODE REVIEW

**Comment by inyono** [comment]
Changed this to a draft PR since we want the contract tests from API side before merging.

**Comment by kulla** [comment]
Todos:

- [ ] add objectId

**Comment by kulla** [comment]
Listener are missing -> I'll implement it with #514 so that you can merge this PR faster.

**Review by inyono — APPROVED** [review]
Contract tests succeed, thanks 👍

**Pull request merged**
