### PR TITLE
Replace Splish editor with Edtr.io

### PR DESCRIPTION
**Pull request by inyono**
Supersedes #22 and #23.

### Open tasks
- [x] Integrate Edtr.io in client
- [x] Integrate Edtr.io in server
  - [x] Especially: fake plugins for every content type as discussed
  - [ ] https://github.com/serlo/athene2/pull/884

### Before merging / releasing
- [ ] Test every content type (both legacy to Edtr.io & Splish Editor to Edtr.io)
- [ ] Test pages
- [ ] Test profiles
- [x] If possible, wait for 100% Kubernetes because legacy backend has completely different deployment process for editor-renderer
- [x] (Is always importFromHtml a breaking change?)
- [x] (Check Backward-compatibility)

### CODE REVIEW

**Comment by inyono** [comment]
Pushed a couple of fixes, `editor-renderer` fails for some easy Splish editor state, though. Let's look into that together, might be missing something simple...

**Comment by Knorrke** [comment]
`editor-renderer` should be fixed now, also rebased on master

**Comment by inyono** [comment]
Need to explore why `athene2-assets` doesn't build anymore

**Comment by inyono** [comment]
Merged to get this into staging :) Still needs some polishing before going into production, though.

**Pull request merged**
