### PR TITLE
API: Remove cache instead of updating it

### PR DESCRIPTION
**Pull request by kulla**
Closes https://github.com/serlo/serlo.org/issues/657

### CODE REVIEW

**Review by inyono — CHANGES_REQUESTED** [review]
Shouldn't we be able to remove `setUuid`?

**Comment by kulla** [comment]
> Shouldn't we be able to remove `setUuid`?

I only removed setUuid() at places where entities might be envolved. Here is the remaining changes: https://github.com/serlo/serlo.org/pull/659 Maybe we want to wait to see how the effects will be in production...

**Comment by kulla** [comment]
@inyono What do you when we change `removeKey` to `updateKey` so that the key get's updated via SWR?

**Comment by inyono** [comment]
> @inyono What do you when we change `removeKey` to `updateKey` so that the key get's updated via SWR?

We could do that, sure.

**Review by inyono — APPROVED** [review]

**Comment by kulla** [comment]
@inyono This PR is now also live in production. When everything works fine we can also merge https://github.com/serlo/serlo.org/pull/659

**Pull request merged**
