### PR TITLE
noindex for legacy

### PR DESCRIPTION
**Pull request by elbotho**
for #651
any objections?
is that a bad idea? :D

### CODE REVIEW

**Comment by kulla** [comment]
Lets talk about this tomorrow in the dev meeting...

**Review by kulla — APPROVED** [review]
Okay as promised I have looked to other solutions:

* https://www.gsqi.com/marketing-blog/google-ignore-rel-canonical-different-content/ explains why it happens and suggests the solution with `noindex, follow`

**Comment by kulla** [comment]
I accidentally sent the comment too early. Here are the missing links:

**Comment by kulla** [comment]
I accidentally sent the comment too early. Here are the missing links: 

* https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls gives a good overview especially the video https://youtu.be/gEWkYTPSEjs
* Also https://i83.uk/google-appears-good-at-ignoring-canonical-tags-on-non-equivalent-pages/ shows that Google might store two urls as different records when though there is a canonical link between them

What happens: Google thinks that the legacy and the frontend version are different site due to the different site structure even though there is a canonical link between them. (The source of google states that the two site need to be almost the same). Thus this is the best solution until we migrate the content api to the new frontend

**Comment by elbotho** [comment]
thanks @kulla !

**Pull request merged**
