### PR TITLE
Remove route /user/public

### PR DESCRIPTION
**Pull request by kulla**
Follow up of https://github.com/serlo/serlo.org-cloudflare-worker/pull/209 with which the route /user/public can never be reached.

### CODE REVIEW

**Comment by inyono** [comment]
Does this also work correctly for logged-in users (that may be redirected to the legacy frontend at the moment)?

**Comment by Entkenntnis** [comment]
"Eigenes Profil" directs to user profile directly, without /user/public, so frontend is fine

**Comment by inyono** [comment]
> "Eigenes Profil" directs to user profile directly, without /user/public, so frontend is fine

I'm talking about legacy. I.e. does it work for users that are logged in and are still served the legacy system.

**Comment by kulla** [comment]
> Does this also work correctly for logged-in users (that may be redirected to the legacy frontend at the moment)?

Yes. `/user/public` is a redirect to the profile route `/user/:id/:username` which is the same as `/user/me` without the navigation left with buttons like `change password`, `edit profile`, etc. This PR would delete the button `public profile` and thus it would be harder for users to get to their public profile view without navigation. However I think that's okay (since they see everything) and it is planned to serve the new design to all logged in users in two weeks anyway...

**Comment by kulla** [comment]
(In the new design there is no distinction between a view on the user profile without and with a navigation -> both views are integrated in one)

**Review by inyono — APPROVED** [review]

**Pull request merged**
