### PR TITLE
Fix redo button 

### LINKED ISSUE #565: Redo button is not working

### PR DESCRIPTION
**Pull request by kulla**
Closes #565

### CODE REVIEW

**Comment by kulla** [comment]
@inyono After updating edtr.io to `2.0.0-beta.0` I cannot import `hasRedoActions()` or `hasUndoActions()` from `@edtr-io/store`. I can see the changes in `node_modules/@edtr-io/store/src/history/reducer.ts` however the string `hasRedoActions` is missing in `node_modules/@edtr-io/store/dist/store.cjs.development.js` Can you have a look?

**Comment by inyono** [comment]
Looks okay at first glance, need to review what happened there. Good that I made a prerelease I guess...  Sorry about that, I'll keep you updated.

**Comment by inyono** [comment]
> Looks okay at first glance, need to review what happened there. Good that I made a prerelease I guess... Sorry about that, I'll keep you updated.

Fixed with `2.0.0-beta.1`.

**Comment by kulla** [comment]
> > Looks okay at first glance, need to review what happened there. Good that I made a prerelease I guess... Sorry about that, I'll keep you updated.
> 
> Fixed with `2.0.0-beta.1`.

Worked. Ready for merge. @inyono

**Review by inyono — APPROVED** [review]

**Pull request merged**
